stages:
  - build

before_script:
  - node -v
  - yarn

build:
  stage: build
  cache:
    key:
      files:
        - yarn.lock
    paths:
      - node_modules
  script:
    - yarn lint
    - yarn build:dev